name: CI and Deploy to GitHub Pages

on:
  push:
    branches:
      - dev # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.email "bouraoui99261855@gmail.com"
          git config --global user.name "bouraouii"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn global add gh-pages
          gh-pages -d build
